spring:
  application:
    name: spring-boot-homework

  datasource:
    url: jdbc:postgresql://localhost:5432/student_api_db
    username: appuser
    password: secretpassword

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/rish-student-system-realm

server:
  port: 8080